version: '3'

services:
  nginx:
    container_name: Nginx
    image: 'nginx:alpine'
    volumes:
      - './html:/usr/share/nginx/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/vhost:/etc/nginx/vhost'
    ports:
      - 80:80
    restart: always
    depends_on:
      - kibana
      - node

  elasticsearch:
    container_name: Elasticsearch
    image: 'elasticsearch:6.5.4'
    restart: always

  node:
    container_name: Node
    build: ./node
    restart: always
    depends_on:
      - fluentd

  fluentd:
    container_name: Fluentd
    build: ./fluentd
    volumes:
      - ./fluentd:/fluentd/etc/
    restart: always
    depends_on:
      - elasticsearch

  kibana:
    container_name: 'Kibana'
    image: kibana:6.5.4
    restart: always
    depends_on:
      - fluentd
    environment:
      ELASTICSEARCH_URL: http://Elasticsearch:9200